var annotated_dup =
[
    [ "px4_ros2", null, [
      [ "default_actions", null, [
        [ "ChangeSettings", "classpx4__ros2_1_1default__actions_1_1ChangeSettings.html", "classpx4__ros2_1_1default__actions_1_1ChangeSettings" ],
        [ "Hold", "classpx4__ros2_1_1default__actions_1_1Hold.html", "classpx4__ros2_1_1default__actions_1_1Hold" ],
        [ "Land", "classpx4__ros2_1_1default__actions_1_1Land.html", "classpx4__ros2_1_1default__actions_1_1Land" ],
        [ "OnFailure", "classpx4__ros2_1_1default__actions_1_1OnFailure.html", null ],
        [ "OnResume", "classpx4__ros2_1_1default__actions_1_1OnResume.html", null ],
        [ "Rtl", "classpx4__ros2_1_1default__actions_1_1Rtl.html", "classpx4__ros2_1_1default__actions_1_1Rtl" ],
        [ "Takeoff", "classpx4__ros2_1_1default__actions_1_1Takeoff.html", null ]
      ] ],
      [ "events", null, [
        [ "LogLevels", "structpx4__ros2_1_1events_1_1LogLevels.html", null ]
      ] ],
      [ "multicopter", null, [
        [ "WaypointTrajectoryExecutor", "classpx4__ros2_1_1multicopter_1_1WaypointTrajectoryExecutor.html", null ]
      ] ],
      [ "util", null, [
        [ "Overloaded", "structpx4__ros2_1_1util_1_1Overloaded.html", null ]
      ] ],
      [ "ActionArguments", "classpx4__ros2_1_1ActionArguments.html", "classpx4__ros2_1_1ActionArguments" ],
      [ "ActionHandler", "classpx4__ros2_1_1ActionHandler.html", "classpx4__ros2_1_1ActionHandler" ],
      [ "ActionInterface", "classpx4__ros2_1_1ActionInterface.html", "classpx4__ros2_1_1ActionInterface" ],
      [ "ActionItem", "structpx4__ros2_1_1ActionItem.html", null ],
      [ "ActionStateKeeper", "classpx4__ros2_1_1ActionStateKeeper.html", null ],
      [ "AttitudeSetpointType", "classpx4__ros2_1_1AttitudeSetpointType.html", "classpx4__ros2_1_1AttitudeSetpointType" ],
      [ "Battery", "classpx4__ros2_1_1Battery.html", "classpx4__ros2_1_1Battery" ],
      [ "ConfigOverrides", "classpx4__ros2_1_1ConfigOverrides.html", null ],
      [ "Context", "classpx4__ros2_1_1Context.html", null ],
      [ "DirectActuatorsSetpointType", "classpx4__ros2_1_1DirectActuatorsSetpointType.html", "classpx4__ros2_1_1DirectActuatorsSetpointType" ],
      [ "Exception", "classpx4__ros2_1_1Exception.html", null ],
      [ "FwControlConfiguration", "structpx4__ros2_1_1FwControlConfiguration.html", "structpx4__ros2_1_1FwControlConfiguration" ],
      [ "FwLateralLongitudinalSetpoint", "structpx4__ros2_1_1FwLateralLongitudinalSetpoint.html", null ],
      [ "FwLateralLongitudinalSetpointType", "classpx4__ros2_1_1FwLateralLongitudinalSetpointType.html", "classpx4__ros2_1_1FwLateralLongitudinalSetpointType" ],
      [ "GlobalPositionMeasurement", "structpx4__ros2_1_1GlobalPositionMeasurement.html", "structpx4__ros2_1_1GlobalPositionMeasurement" ],
      [ "GlobalPositionMeasurementInterface", "classpx4__ros2_1_1GlobalPositionMeasurementInterface.html", "classpx4__ros2_1_1GlobalPositionMeasurementInterface" ],
      [ "HasMessageVersion", "structpx4__ros2_1_1HasMessageVersion.html", null ],
      [ "HasMessageVersion< T, std::void_t< decltype(T::MESSAGE_VERSION)> >", "structpx4__ros2_1_1HasMessageVersion_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1MESSAGE__VERSION_08_4_01_4.html", null ],
      [ "HealthAndArmingCheckReporter", "classpx4__ros2_1_1HealthAndArmingCheckReporter.html", null ],
      [ "HealthAndArmingChecks", "classpx4__ros2_1_1HealthAndArmingChecks.html", "classpx4__ros2_1_1HealthAndArmingChecks" ],
      [ "HomePosition", "classpx4__ros2_1_1HomePosition.html", "classpx4__ros2_1_1HomePosition" ],
      [ "HomePositionSetter", "classpx4__ros2_1_1HomePositionSetter.html", "classpx4__ros2_1_1HomePositionSetter" ],
      [ "LandDetected", "classpx4__ros2_1_1LandDetected.html", "classpx4__ros2_1_1LandDetected" ],
      [ "LocalPositionMeasurement", "structpx4__ros2_1_1LocalPositionMeasurement.html", "structpx4__ros2_1_1LocalPositionMeasurement" ],
      [ "LocalPositionMeasurementInterface", "classpx4__ros2_1_1LocalPositionMeasurementInterface.html", "classpx4__ros2_1_1LocalPositionMeasurementInterface" ],
      [ "ManualControlInput", "classpx4__ros2_1_1ManualControlInput.html", "classpx4__ros2_1_1ManualControlInput" ],
      [ "MapProjection", "classpx4__ros2_1_1MapProjection.html", "classpx4__ros2_1_1MapProjection" ],
      [ "MessageCompatibilityTopic", "structpx4__ros2_1_1MessageCompatibilityTopic.html", "structpx4__ros2_1_1MessageCompatibilityTopic" ],
      [ "Mission", "classpx4__ros2_1_1Mission.html", null ],
      [ "MissionDefaults", "structpx4__ros2_1_1MissionDefaults.html", null ],
      [ "MissionExecutor", "classpx4__ros2_1_1MissionExecutor.html", "classpx4__ros2_1_1MissionExecutor" ],
      [ "MissionFileMonitor", "classpx4__ros2_1_1MissionFileMonitor.html", null ],
      [ "ModeBase", "classpx4__ros2_1_1ModeBase.html", "classpx4__ros2_1_1ModeBase" ],
      [ "ModeExecutorBase", "classpx4__ros2_1_1ModeExecutorBase.html", "classpx4__ros2_1_1ModeExecutorBase" ],
      [ "MulticopterGotoGlobalSetpointType", "classpx4__ros2_1_1MulticopterGotoGlobalSetpointType.html", "classpx4__ros2_1_1MulticopterGotoGlobalSetpointType" ],
      [ "MulticopterGotoSetpointType", "classpx4__ros2_1_1MulticopterGotoSetpointType.html", "classpx4__ros2_1_1MulticopterGotoSetpointType" ],
      [ "NavigationInterfaceInvalidArgument", "classpx4__ros2_1_1NavigationInterfaceInvalidArgument.html", null ],
      [ "NavigationItem", "structpx4__ros2_1_1NavigationItem.html", null ],
      [ "NodeWithMode", "classpx4__ros2_1_1NodeWithMode.html", null ],
      [ "NodeWithModeExecutor", "classpx4__ros2_1_1NodeWithModeExecutor.html", null ],
      [ "Odometry", "classpx4__ros2_1_1Odometry.html", "classpx4__ros2_1_1Odometry" ],
      [ "OdometryAirspeed", "classpx4__ros2_1_1OdometryAirspeed.html", null ],
      [ "OdometryAngularVelocity", "classpx4__ros2_1_1OdometryAngularVelocity.html", "classpx4__ros2_1_1OdometryAngularVelocity" ],
      [ "OdometryAttitude", "classpx4__ros2_1_1OdometryAttitude.html", "classpx4__ros2_1_1OdometryAttitude" ],
      [ "OdometryGlobalPosition", "classpx4__ros2_1_1OdometryGlobalPosition.html", "classpx4__ros2_1_1OdometryGlobalPosition" ],
      [ "OdometryLocalPosition", "classpx4__ros2_1_1OdometryLocalPosition.html", "classpx4__ros2_1_1OdometryLocalPosition" ],
      [ "PeripheralActuatorControls", "classpx4__ros2_1_1PeripheralActuatorControls.html", "classpx4__ros2_1_1PeripheralActuatorControls" ],
      [ "PositionMeasurementInterfaceBase", "classpx4__ros2_1_1PositionMeasurementInterfaceBase.html", "classpx4__ros2_1_1PositionMeasurementInterfaceBase" ],
      [ "RatesSetpointType", "classpx4__ros2_1_1RatesSetpointType.html", null ],
      [ "RequirementFlags", "structpx4__ros2_1_1RequirementFlags.html", "structpx4__ros2_1_1RequirementFlags" ],
      [ "RoverPositionSetpointType", "classpx4__ros2_1_1RoverPositionSetpointType.html", "classpx4__ros2_1_1RoverPositionSetpointType" ],
      [ "RoverSpeedAttitudeSetpointType", "classpx4__ros2_1_1RoverSpeedAttitudeSetpointType.html", "classpx4__ros2_1_1RoverSpeedAttitudeSetpointType" ],
      [ "RoverSpeedRateSetpointType", "classpx4__ros2_1_1RoverSpeedRateSetpointType.html", "classpx4__ros2_1_1RoverSpeedRateSetpointType" ],
      [ "RoverSpeedSteeringSetpointType", "classpx4__ros2_1_1RoverSpeedSteeringSetpointType.html", "classpx4__ros2_1_1RoverSpeedSteeringSetpointType" ],
      [ "RoverThrottleAttitudeSetpointType", "classpx4__ros2_1_1RoverThrottleAttitudeSetpointType.html", "classpx4__ros2_1_1RoverThrottleAttitudeSetpointType" ],
      [ "RoverThrottleRateSetpointType", "classpx4__ros2_1_1RoverThrottleRateSetpointType.html", "classpx4__ros2_1_1RoverThrottleRateSetpointType" ],
      [ "RoverThrottleSteeringSetpointType", "classpx4__ros2_1_1RoverThrottleSteeringSetpointType.html", "classpx4__ros2_1_1RoverThrottleSteeringSetpointType" ],
      [ "SetpointBase", "classpx4__ros2_1_1SetpointBase.html", "classpx4__ros2_1_1SetpointBase" ],
      [ "Subscription", "classpx4__ros2_1_1Subscription.html", "classpx4__ros2_1_1Subscription" ],
      [ "TrajectoryExecutorInterface", "classpx4__ros2_1_1TrajectoryExecutorInterface.html", "classpx4__ros2_1_1TrajectoryExecutorInterface" ],
      [ "TrajectoryOptions", "structpx4__ros2_1_1TrajectoryOptions.html", "structpx4__ros2_1_1TrajectoryOptions" ],
      [ "TrajectorySetpoint", "structpx4__ros2_1_1TrajectorySetpoint.html", "structpx4__ros2_1_1TrajectorySetpoint" ],
      [ "TrajectorySetpointType", "classpx4__ros2_1_1TrajectorySetpointType.html", "classpx4__ros2_1_1TrajectorySetpointType" ],
      [ "VehicleCommandSender", "classpx4__ros2_1_1VehicleCommandSender.html", "classpx4__ros2_1_1VehicleCommandSender" ],
      [ "VehicleStatus", "classpx4__ros2_1_1VehicleStatus.html", "classpx4__ros2_1_1VehicleStatus" ],
      [ "VTOL", "classpx4__ros2_1_1VTOL.html", "classpx4__ros2_1_1VTOL" ],
      [ "VTOLConfig", "structpx4__ros2_1_1VTOLConfig.html", "structpx4__ros2_1_1VTOLConfig" ],
      [ "VtolStatus", "classpx4__ros2_1_1VtolStatus.html", "classpx4__ros2_1_1VtolStatus" ],
      [ "Waypoint", "structpx4__ros2_1_1Waypoint.html", null ]
    ] ],
    [ "SharedSubscription", "classSharedSubscription.html", null ]
];