var annotated_dup =
[
    [ "px4_ros2", null, [
      [ "events", null, [
        [ "LogLevels", "structpx4__ros2_1_1events_1_1LogLevels.html", "structpx4__ros2_1_1events_1_1LogLevels" ]
      ] ],
      [ "Context", "classpx4__ros2_1_1Context.html", "classpx4__ros2_1_1Context" ],
      [ "RequirementFlags", "structpx4__ros2_1_1RequirementFlags.html", "structpx4__ros2_1_1RequirementFlags" ],
      [ "SetpointBase", "classpx4__ros2_1_1SetpointBase.html", "classpx4__ros2_1_1SetpointBase" ],
      [ "HealthAndArmingCheckReporter", "classpx4__ros2_1_1HealthAndArmingCheckReporter.html", "classpx4__ros2_1_1HealthAndArmingCheckReporter" ],
      [ "HealthAndArmingChecks", "classpx4__ros2_1_1HealthAndArmingChecks.html", "classpx4__ros2_1_1HealthAndArmingChecks" ],
      [ "ManualControlInput", "classpx4__ros2_1_1ManualControlInput.html", "classpx4__ros2_1_1ManualControlInput" ],
      [ "MessageCompatibilityTopic", "structpx4__ros2_1_1MessageCompatibilityTopic.html", "structpx4__ros2_1_1MessageCompatibilityTopic" ],
      [ "ModeBase", "classpx4__ros2_1_1ModeBase.html", "classpx4__ros2_1_1ModeBase" ],
      [ "ModeExecutorBase", "classpx4__ros2_1_1ModeExecutorBase.html", "classpx4__ros2_1_1ModeExecutorBase" ],
      [ "NodeWithMode", "classpx4__ros2_1_1NodeWithMode.html", "classpx4__ros2_1_1NodeWithMode" ],
      [ "NodeWithModeExecutor", "classpx4__ros2_1_1NodeWithModeExecutor.html", "classpx4__ros2_1_1NodeWithModeExecutor" ],
      [ "ConfigOverrides", "classpx4__ros2_1_1ConfigOverrides.html", "classpx4__ros2_1_1ConfigOverrides" ],
      [ "PeripheralActuatorControls", "classpx4__ros2_1_1PeripheralActuatorControls.html", "classpx4__ros2_1_1PeripheralActuatorControls" ],
      [ "DirectActuatorsSetpointType", "classpx4__ros2_1_1DirectActuatorsSetpointType.html", "classpx4__ros2_1_1DirectActuatorsSetpointType" ],
      [ "AttitudeSetpointType", "classpx4__ros2_1_1AttitudeSetpointType.html", "classpx4__ros2_1_1AttitudeSetpointType" ],
      [ "RatesSetpointType", "classpx4__ros2_1_1RatesSetpointType.html", "classpx4__ros2_1_1RatesSetpointType" ],
      [ "RoverPositionSetpointType", "classpx4__ros2_1_1RoverPositionSetpointType.html", "classpx4__ros2_1_1RoverPositionSetpointType" ],
      [ "RoverSpeedAttitudeSetpointType", "classpx4__ros2_1_1RoverSpeedAttitudeSetpointType.html", "classpx4__ros2_1_1RoverSpeedAttitudeSetpointType" ],
      [ "RoverSpeedRateSetpointType", "classpx4__ros2_1_1RoverSpeedRateSetpointType.html", "classpx4__ros2_1_1RoverSpeedRateSetpointType" ],
      [ "RoverSpeedSteeringSetpointType", "classpx4__ros2_1_1RoverSpeedSteeringSetpointType.html", "classpx4__ros2_1_1RoverSpeedSteeringSetpointType" ],
      [ "RoverThrottleAttitudeSetpointType", "classpx4__ros2_1_1RoverThrottleAttitudeSetpointType.html", "classpx4__ros2_1_1RoverThrottleAttitudeSetpointType" ],
      [ "RoverThrottleRateSetpointType", "classpx4__ros2_1_1RoverThrottleRateSetpointType.html", "classpx4__ros2_1_1RoverThrottleRateSetpointType" ],
      [ "RoverThrottleSteeringSetpointType", "classpx4__ros2_1_1RoverThrottleSteeringSetpointType.html", "classpx4__ros2_1_1RoverThrottleSteeringSetpointType" ],
      [ "TrajectorySetpointType", "classpx4__ros2_1_1TrajectorySetpointType.html", "classpx4__ros2_1_1TrajectorySetpointType" ],
      [ "TrajectorySetpoint", "structpx4__ros2_1_1TrajectorySetpoint.html", "structpx4__ros2_1_1TrajectorySetpoint" ],
      [ "FwLateralLongitudinalSetpointType", "classpx4__ros2_1_1FwLateralLongitudinalSetpointType.html", "classpx4__ros2_1_1FwLateralLongitudinalSetpointType" ],
      [ "FwLateralLongitudinalSetpoint", "structpx4__ros2_1_1FwLateralLongitudinalSetpoint.html", "structpx4__ros2_1_1FwLateralLongitudinalSetpoint" ],
      [ "FwControlConfiguration", "structpx4__ros2_1_1FwControlConfiguration.html", "structpx4__ros2_1_1FwControlConfiguration" ],
      [ "GotoSetpointType", "classpx4__ros2_1_1GotoSetpointType.html", "classpx4__ros2_1_1GotoSetpointType" ],
      [ "GotoGlobalSetpointType", "classpx4__ros2_1_1GotoGlobalSetpointType.html", "classpx4__ros2_1_1GotoGlobalSetpointType" ],
      [ "VTOLConfig", "structpx4__ros2_1_1VTOLConfig.html", "structpx4__ros2_1_1VTOLConfig" ],
      [ "VTOL", "classpx4__ros2_1_1VTOL.html", "classpx4__ros2_1_1VTOL" ],
      [ "GlobalPositionMeasurement", "structpx4__ros2_1_1GlobalPositionMeasurement.html", "structpx4__ros2_1_1GlobalPositionMeasurement" ],
      [ "GlobalPositionMeasurementInterface", "classpx4__ros2_1_1GlobalPositionMeasurementInterface.html", "classpx4__ros2_1_1GlobalPositionMeasurementInterface" ],
      [ "LocalPositionMeasurement", "structpx4__ros2_1_1LocalPositionMeasurement.html", "structpx4__ros2_1_1LocalPositionMeasurement" ],
      [ "LocalPositionMeasurementInterface", "classpx4__ros2_1_1LocalPositionMeasurementInterface.html", "classpx4__ros2_1_1LocalPositionMeasurementInterface" ],
      [ "NavigationInterfaceInvalidArgument", "classpx4__ros2_1_1NavigationInterfaceInvalidArgument.html", "classpx4__ros2_1_1NavigationInterfaceInvalidArgument" ],
      [ "PositionMeasurementInterfaceBase", "classpx4__ros2_1_1PositionMeasurementInterfaceBase.html", "classpx4__ros2_1_1PositionMeasurementInterfaceBase" ],
      [ "OdometryAirspeed", "classpx4__ros2_1_1OdometryAirspeed.html", "classpx4__ros2_1_1OdometryAirspeed" ],
      [ "OdometryAngularVelocity", "classpx4__ros2_1_1OdometryAngularVelocity.html", "classpx4__ros2_1_1OdometryAngularVelocity" ],
      [ "OdometryAttitude", "classpx4__ros2_1_1OdometryAttitude.html", "classpx4__ros2_1_1OdometryAttitude" ],
      [ "OdometryGlobalPosition", "classpx4__ros2_1_1OdometryGlobalPosition.html", "classpx4__ros2_1_1OdometryGlobalPosition" ],
      [ "OdometryLocalPosition", "classpx4__ros2_1_1OdometryLocalPosition.html", "classpx4__ros2_1_1OdometryLocalPosition" ],
      [ "MapProjection", "classpx4__ros2_1_1MapProjection.html", "classpx4__ros2_1_1MapProjection" ],
      [ "HasMessageVersion", "structpx4__ros2_1_1HasMessageVersion.html", null ],
      [ "HasMessageVersion< T, std::void_t< decltype(T::MESSAGE_VERSION)> >", "structpx4__ros2_1_1HasMessageVersion_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1MESSAGE__VERSION_08_4_01_4.html", null ],
      [ "Subscription", "classpx4__ros2_1_1Subscription.html", "classpx4__ros2_1_1Subscription" ],
      [ "Battery", "classpx4__ros2_1_1Battery.html", "classpx4__ros2_1_1Battery" ],
      [ "HomePosition", "classpx4__ros2_1_1HomePosition.html", "classpx4__ros2_1_1HomePosition" ],
      [ "LandDetected", "classpx4__ros2_1_1LandDetected.html", "classpx4__ros2_1_1LandDetected" ],
      [ "VehicleStatus", "classpx4__ros2_1_1VehicleStatus.html", "classpx4__ros2_1_1VehicleStatus" ],
      [ "VtolStatus", "classpx4__ros2_1_1VtolStatus.html", "classpx4__ros2_1_1VtolStatus" ]
    ] ]
];