name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
      - doxygen
  pull_request:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: [runs-on,"runner=${{ vars.RUNSON_CI_RUNNER_DEFAULT }}","run-id=${{ github.run_id }}"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Run doxygen
        run: ./scripts/run-doxygen.sh

      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
